os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/install-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/build-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/test-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/packages.sh
  - ALL=$([ "$TRAVIS_EVENT_TYPE" == "cron" ] && echo "true") || true
  - source packages.sh --commit-range=$TRAVIS_COMMIT_RANGE --all=$ALL
env:
  - PACKAGE=ed_perception
  - PACKAGE=ed_perception_msgs

install:
  - bash install-package.sh --package=$PACKAGE --branch=$TRAVIS_BRANCH --commit=$TRAVIS_COMMIT --pullrequest=$TRAVIS_PULL_REQUEST

before_script:
  - bash build-package.sh --package=$PACKAGE

script:
  - bash test-package.sh --package=$PACKAGE
