sudo: true

language: cpp

services:
  - docker

before_install:
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/install-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/build-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/packages.sh
  # Determine packages modified in this commit
  - source packages.sh --commit-range=$TRAVIS_COMMIT_RANGE

env:
  - PACKAGE=ed_perception
  - PACKAGE=ed_perception_msgs

install:
  - bash install-package.sh --package=$PACKAGE --branch=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --commit=$TRAVIS_COMMIT --pullrequest=$TRAVIS_PULL_REQUEST

script:
  - bash build-package.sh --package=$PACKAGE
